import { Role } from '@core';
import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [Role.All],
    submenu: [],
  },

  // Admin Modules
  {
    path: '',
    title: 'Inicio',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: [
      {
        path: '/admin/dashboard/main',
        title: 'Inicio',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Gestion usuarios',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: [
      {
        path: '/admin/gestionar-usuarios/usuarios/all-usuarios',
        title: 'Usuarios',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/gestionar-usuarios/personas/all-personas',
        title: 'Personas',
        iconType: '',
        icon: 'face',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/gestionar-usuarios/generos/all-generos',
        title: 'Generos',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/gestionar-usuarios/tipos-documentos/all-tiposdocumentos',
        title: 'Tipos de documento',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Gestión sig. alarma',
    iconType: 'material-icons-two-tone',
    icon: 'add_alert',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: [
      {
        path: '/admin/gestion-signos-alarma/all-signosalarma',
        title: 'Signos de alarma',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Gestión temas',
    iconType: 'material-icons-two-tone',
    icon: 'color_lens',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: [
      {
        path: '/admin/gestion-temas/all-temas',
        title: 'Temas y subtemas',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Instituciones',
    iconType: 'material-icons-two-tone',
    icon: 'local_convenience_store',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: [
      {
        path: '/admin/instituciones/tipos-instituciones/all-tiposinstituciones',
        title: 'Tipos de instituciones',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/instituciones/servicios/all-servicios',
        title: 'Servicios',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/instituciones/instituciones/all-instituciones',
        title: 'Instituciones',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '/admin/gestion-logros/all-logros',
    title: 'Logros',
    iconType: 'material-icons-two-tone',
    icon: 'stars',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: []
  },
  {
    path: '/admin/gestion-material-apoyo',
    title: 'Material de apoyo',
    iconType: 'material-icons-two-tone',
    icon: 'support_agent',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Admin],
    submenu: []
  },
  // {
  //   path: '',
  //   title: 'MENUITEMS.ROOMS.TEXT',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'favorite',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Admin],
  //   submenu: [
  //     {
  //       path: '/admin/room/all-rooms',
  //       title: 'MENUITEMS.ROOMS.LIST.ALLOTED-ROOMS',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: '',
  //   title: 'MENUITEMS.INVENTORY.TEXT',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'assignment',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Admin],
  //   submenu: [
  //     {
  //       path: '/admin/inventory/item-stock-list',
  //       title: 'MENUITEMS.INVENTORY.LIST.ITEM-STOCK-LIST',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

  // ================================================= Doctor Modules =========================================================================
  {
    path: '/doctor/dashboard',
    title: 'MENUITEMS.DOCTOR.DASHBOARD',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Doctor],
    submenu: [],
  },
  // {
  //   path: '/doctor/appointments',
  //   title: 'MENUITEMS.DOCTOR.APPOINTMENTS',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'assignment',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  // {
  //   path: '/doctor/doctors',
  //   title: 'MENUITEMS.DOCTOR.DOCTORS',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'supervised_user_circle',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  // {
  //   path: '/doctor/patients',
  //   title: 'MENUITEMS.DOCTOR.PATIENTS',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'face',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  
  // {
  //   path: '/apps/chat',
  //   title: 'MENUITEMS.DOCTOR.CHAT',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'chat',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  // {
  //   path: '/doctor/inventory/item-stock-list',
  //   title: 'MENUITEMS.INVENTORY.TEXT',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'assignment',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  {
    path: '/admin/gestionar-usuarios/personas/all-personas',
    title: 'MENUITEMS.DOCTOR.PERSON',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Doctor],
    submenu: [],
  },
  // {
  //   path: '/doctor/settings',
  //   title: 'MENUITEMS.DOCTOR.SETTINGS',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'settings',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [Role.Doctor],
  //   submenu: [],
  // },
  //PatientModules
  {
    path: '/patient/dashboard',
    title: 'Inicio',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Patient],
    submenu: [],
  },
  // {
  //   path: '/patient/usuarios/all-usuarios',
  //   title: 'Usuarios',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'people_alt',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [''],
  //   submenu: [],
  // },
  // {
  //   path: '/patient/personas/all-personas',
  //   title: 'MENUITEMS.DOCTOR.PERSON',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'face',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: [''],
  //   submenu: [],
  // },
  {
    path: '/patient/room/all-rooms',
    title: 'Situaciones',
    iconType: 'material-icons-two-tone',
    icon: 'favorite',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Patient],
    submenu: [],
  },
  {
    path: '/patient/achievement',
    title: 'Mis logros',
    iconType: 'material-icons-two-tone',
    icon: 'flag',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Patient],
    submenu: [],
  },
  {
    path: '/patient/inventory/item-stock-list',
    title: 'MENUITEMS.INVENTORY.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Patient],
    submenu: [],
  },
  {
    path: '/patient/maternal-kit',
    title: 'MENUITEMS.MATERNALKIT.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'shop',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [Role.Patient],
    submenu: [],
  },

  // Common Modules

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [Role.Doctor, Role.Patient],
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Calendario',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: [Role.Doctor, Role.Patient],
    submenu: [],
  },
  {
    path: 'task',
    title: 'Task',
    iconType: 'material-icons-two-tone',
    icon: 'fact_check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [],
    submenu: [],
  },
  {
    path: 'contacts',
    title: 'Contacts',
    iconType: 'material-icons-two-tone',
    icon: 'contacts',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [],
    submenu: [],
  },
  {
    path: '',
    title: 'Email',
    iconType: 'material-icons-two-tone',
    icon: 'email',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [],
    submenu: [
      {
        path: '/email/inbox',
        title: 'Inbox',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/email/compose',
        title: 'Compose',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/email/read-mail',
        title: 'Read Email',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
];
